name: Release model-training
on:
    push:
        tags:
            - 'v*.*.*'  

env:
  PYTHON_VERSION: '3.12.2'

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install setuptools wheel twine
                
            - name: Train and save model
              run: python src/train.py

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                  models/*.pkl
                  bow/*.pkl
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}