name: Model training tests

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            make requirements

      - name: Write service account JSON
        run: |
          mkdir -p .dvc/tmp
          echo "${{ secrets.GDRIVE_SERVICEACCOUNT_SECRET }}" | base64 -d > .dvc/tmp/remlaproject-sa.json

      - name: Pull DVC data
        run: dvc pull

      - name: Lint with pylint
        run: pylint training

      - name: Run tests with coverage
        run: |
          pytest --cov=training --cov-report=term-missing --cov-report=xml
          coverage xml
          coverage-badge -o coverage.svg
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet || (git add coverage.svg && git commit -m "Updated coverage.svg" && git commit -m "Updated coverage.svg")
          git push origin HEAD:${GITHUB_HEAD_REF}

      - uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: training
          python-version: 3.11  