name: Model training tests

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            make requirements
            python -m pip install -e .
            pip install pytest coverage pytest-cov pylint memory-profiler loguru
      
      - name: Install DVC and dependencies
        run: pip install dvc dvc[gdrive]

      - name: Write service account JSON
        run: |
          mkdir -p .dvc/tmp
          echo "${{ secrets.GDRIVE_SERVICEACCOUNT_SECRET }}" | base64 -d > .dvc/tmp/remlaproject-sa.json

      - name: Debug JSON content
        run: |
          head -n 2 .dvc/tmp/remlaproject-sa.json

      - name: Pull DVC data
        run: dvc pull

      - name: Lint with pylint
        run: pylint training

      - name: Run tests with coverage
        run: pytest --cov=training --cov-report=term-missing